# Form implementation generated from reading ui file 'abaut.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(618, 589)
        Dialog.setMinimumSize(QtCore.QSize(618, 589))
        Dialog.setMaximumSize(QtCore.QSize(618, 589))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imagenes/Figure_2-.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 20, 67, 17))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(10, 40, 301, 191))
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 250, 141, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("imagenes/FRANCISCO RACEDO NIEBLES_0.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(320, 40, 281, 192))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(390, 250, 141, 131))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("imagenes/MARIOMONTERO.jpeg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(290, 480, 61, 31))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(parent=Dialog)
        self.label_8.setGeometry(QtCore.QRect(10, 500, 131, 71))
        self.label_8.setAutoFillBackground(False)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("imagenes/acreditacion logo 2019.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setWordWrap(False)
        self.label_8.setOpenExternalLinks(False)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(parent=Dialog)
        self.label_7.setGeometry(QtCore.QRect(530, 540, 61, 15))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("imagenes/logo pixel_Mesa de trabajo 11_Mesa de trabajo 1.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setOpenExternalLinks(False)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(270, 510, 91, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setGeometry(QtCore.QRect(220, 540, 171, 17))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Abaut"))
        self.label.setText(_translate("Dialog", "Autores: "))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; color:#666666;\">FRANCISCO RACEDO NIEBLES</span></p>\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; color:#666666;\">Docente Tiempo Completo</span></p>\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; color:#666666;\">Universidad del Atlántico<br />Magister en Ciencias  Físicas<br />Universidad  Industrial de Santander<br />Espectrocopía, Óptica y Emisión Láser-GEOEL</span></p>\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><a href=\"https://scienti.minciencias.gov.co/cvlac/visualizador/generarCurriculoCv.do?cod_rh=0000212997\"><span style=\" text-decoration: underline; color:#0000ff;\">CvLAC</span></a></p>\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; color:#666666;\">Red de Investigación:</span></p>\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; color:#666666;\">ScienTI-Colombia. Colciencias - SBF (Sociedad Brasilera de Física) - OSA (Sociedad Americana de Óptica)</span></p>\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><a href=\"mailto:franciscoracedo@mail.uniatlantico.edu.co\"><span style=\" font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; text-decoration: underline; color:#496e9c;\">franciscoracedo@mail.uniatlantico.edu.co</span></a></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%; font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; text-decoration: underline; color:#496e9c;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; color:#666666;\">MARIO RICARDO MONTERO HURTADO</span></p>\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; color:#666666;\">Estudiante de Física</span></p>\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; color:#666666;\">Universidad del Atlántico</span></p>\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; color:#666666;\"><br />Espectrocopía, Óptica y Emisión Láser-GEOEL</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%; font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; color:#666666;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><a href=\"mailto:franciscoracedo@mail.uniatlantico.edu.co\"><span style=\" font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; text-decoration: underline; color:#496e9c;\">mrmontero@mail.uniatlantico.edu.co</span></a></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:10px; margin-bottom:10px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%; font-family:\'Tahoma\',\'Verdana\',\'Arial\',\'Helvetica\',\'sans-serif\'; font-size:12px; text-decoration: underline; color:#496e9c;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "2021"))
        self.label_5.setText(_translate("Dialog", "Version 1.0"))
        self.label_6.setText(_translate("Dialog", "Licencia Software libre."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
