# Form implementation generated from reading ui file 'tabla.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QIcon

class Ui_tabla(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.resize(780, 460)
        self.setWindowTitle("Table")
        icon = QIcon("../imagenes/Figure_2-.ico")
        self.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QVBoxLayout()
        self.tableView = QtWidgets.QTableView(parent=None)
        self.tableView.resizeColumnsToContents()
        self.gridLayout.addWidget(self.tableView)
        widget = QtWidgets.QWidget()
        widget.setLayout(self.gridLayout)
        self.setCentralWidget(widget)

        self.show()




