# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'v2.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QSlider, QTableView,
    QWidget)

class Ui_Laser(object):
    def setupUi(self, Laser):
        if not Laser.objectName():
            Laser.setObjectName(u"Laser")
        Laser.setEnabled(True)
        Laser.resize(1207, 709)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Laser.sizePolicy().hasHeightForWidth())
        Laser.setSizePolicy(sizePolicy)
        icon = QIcon()
        icon.addFile(u"Figure_2-.ico", QSize(), QIcon.Normal, QIcon.Off)
        Laser.setWindowIcon(icon)
        Laser.setLayoutDirection(Qt.LeftToRight)
        Laser.setStyleSheet(u"")
        Laser.setIconSize(QSize(125, 125))
        Laser.setToolButtonStyle(Qt.ToolButtonFollowStyle)
        Laser.setAnimated(True)
        Laser.setDocumentMode(False)
        self.actionGuardar = QAction(Laser)
        self.actionGuardar.setObjectName(u"actionGuardar")
        self.actionGuardar.setIconVisibleInMenu(True)
        self.actionAbrir_Imagen = QAction(Laser)
        self.actionAbrir_Imagen.setObjectName(u"actionAbrir_Imagen")
        self.actionAbrir_Imagen.setCheckable(False)
        self.actionSelecionar_camara = QAction(Laser)
        self.actionSelecionar_camara.setObjectName(u"actionSelecionar_camara")
        self.actionSelecionar_camara.setCheckable(False)
        self.actionSelecionar_camara.setChecked(False)
        self.actionSelecionar_camara.setEnabled(False)
        self.actionTabla = QAction(Laser)
        self.actionTabla.setObjectName(u"actionTabla")
        self.actionTabla.setEnabled(False)
        self.actionGuardar_tabla = QAction(Laser)
        self.actionGuardar_tabla.setObjectName(u"actionGuardar_tabla")
        self.actionVisualizar_3D = QAction(Laser)
        self.actionVisualizar_3D.setObjectName(u"actionVisualizar_3D")
        self.action3D = QAction(Laser)
        self.action3D.setObjectName(u"action3D")
        self.action2D = QAction(Laser)
        self.action2D.setObjectName(u"action2D")
        self.action2DGuia = QAction(Laser)
        self.action2DGuia.setObjectName(u"action2DGuia")
        self.actionAbaut = QAction(Laser)
        self.actionAbaut.setObjectName(u"actionAbaut")
        self.actionDark_Blue = QAction(Laser)
        self.actionDark_Blue.setObjectName(u"actionDark_Blue")
        self.actionDefault = QAction(Laser)
        self.actionDefault.setObjectName(u"actionDefault")
        self.action2D_Menor = QAction(Laser)
        self.action2D_Menor.setObjectName(u"action2D_Menor")
        self.actionAbrir = QAction(Laser)
        self.actionAbrir.setObjectName(u"actionAbrir")
        self.actionAyuda = QAction(Laser)
        self.actionAyuda.setObjectName(u"actionAyuda")
        self.actionAyuda.setEnabled(True)
        self.actionExportar_reporte = QAction(Laser)
        self.actionExportar_reporte.setObjectName(u"actionExportar_reporte")
        self.actionExportar_reporte.setEnabled(False)
        self.actionTabla_2 = QAction(Laser)
        self.actionTabla_2.setObjectName(u"actionTabla_2")
        self.actionparametros = QAction(Laser)
        self.actionparametros.setObjectName(u"actionparametros")
        self.centralwidget = QWidget(Laser)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setAutoFillBackground(False)
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setObjectName(u"gridLayout")
        self.widget_3 = QWidget(self.centralwidget)
        self.widget_3.setObjectName(u"widget_3")
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy1.setHorizontalStretch(1)
        sizePolicy1.setVerticalStretch(1)
        sizePolicy1.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy1)
        self.widget_3.setMinimumSize(QSize(164, 182))
        self.widget_3.setMaximumSize(QSize(1000, 431))
        self.widget_3.setSizeIncrement(QSize(1, 1))
        self.widget_3.setBaseSize(QSize(433, 331))

        self.gridLayout.addWidget(self.widget_3, 5, 4, 3, 1)

        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setMinimumSize(QSize(0, 0))
        self.label_5.setMaximumSize(QSize(351, 17))
        self.label_5.setBaseSize(QSize(351, 17))

        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 4)

        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setMinimumSize(QSize(0, 0))
        self.label_2.setMaximumSize(QSize(51, 17))
        self.label_2.setBaseSize(QSize(51, 17))

        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)

        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy2)
        self.label_3.setMinimumSize(QSize(0, 0))
        self.label_3.setMaximumSize(QSize(71, 17))
        self.label_3.setBaseSize(QSize(71, 17))

        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)

        self.horizontalSlider = QSlider(self.centralwidget)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        sizePolicy3 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy3)
        self.horizontalSlider.setMinimumSize(QSize(0, 0))
        self.horizontalSlider.setMaximumSize(QSize(270, 21))
        self.horizontalSlider.setMinimum(0)
        self.horizontalSlider.setValue(0)
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.horizontalSlider.setInvertedControls(False)
        self.horizontalSlider.setTickInterval(5)

        self.gridLayout.addWidget(self.horizontalSlider, 1, 1, 1, 3)

        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setMinimumSize(QSize(0, 0))
        self.lineEdit.setMaximumSize(QSize(113, 25))

        self.gridLayout.addWidget(self.lineEdit, 0, 1, 1, 1)

        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setMinimumSize(QSize(0, 0))
        self.label.setMaximumSize(QSize(81, 17))
        self.label.setBaseSize(QSize(81, 17))

        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.tableView = QTableView(self.centralwidget)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setMinimumSize(QSize(0, 0))
        self.tableView.setMaximumSize(QSize(351, 350))
        self.tableView.setBaseSize(QSize(351, 361))
        self.tableView.setGridStyle(Qt.NoPen)

        self.gridLayout.addWidget(self.tableView, 3, 0, 3, 4)

        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setObjectName(u"widget_2")
        sizePolicy1.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy1)
        self.widget_2.setMinimumSize(QSize(164, 182))
        self.widget_2.setMaximumSize(QSize(1000, 431))
        self.widget_2.setSizeIncrement(QSize(1, 1))
        self.widget_2.setBaseSize(QSize(433, 331))

        self.gridLayout.addWidget(self.widget_2, 5, 5, 3, 1)

        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setMinimumSize(QSize(0, 0))
        self.label_6.setMaximumSize(QSize(131, 71))
        self.label_6.setBaseSize(QSize(131, 71))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setPixmap(QPixmap(u"imagenes/acreditacion logo 2019.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setWordWrap(False)
        self.label_6.setOpenExternalLinks(False)

        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 3)

        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        sizePolicy2.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy2)
        self.label_7.setMinimumSize(QSize(0, 0))
        self.label_7.setMaximumSize(QSize(61, 15))
        self.label_7.setBaseSize(QSize(61, 15))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setPixmap(QPixmap(u"imagenes/logo pixel_Mesa de trabajo 11_Mesa de trabajo 1.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setOpenExternalLinks(False)

        self.gridLayout.addWidget(self.label_7, 9, 0, 1, 2)

        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        sizePolicy1.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy1)
        self.widget.setMinimumSize(QSize(164, 182))
        self.widget.setMaximumSize(QSize(1000, 431))
        self.widget.setSizeIncrement(QSize(1, 1))
        self.widget.setBaseSize(QSize(433, 331))

        self.gridLayout.addWidget(self.widget, 0, 5, 5, 1)

        self.widget_4 = QWidget(self.centralwidget)
        self.widget_4.setObjectName(u"widget_4")
        sizePolicy1.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy1)
        self.widget_4.setMinimumSize(QSize(164, 182))
        self.widget_4.setMaximumSize(QSize(1000, 431))
        self.widget_4.setSizeIncrement(QSize(1, 1))
        self.widget_4.setBaseSize(QSize(433, 331))
        self.widget_4.setLayoutDirection(Qt.LeftToRight)

        self.gridLayout.addWidget(self.widget_4, 0, 4, 5, 1)

        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setEnabled(True)
        sizePolicy4 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy4)
        self.pushButton.setMinimumSize(QSize(0, 0))
        self.pushButton.setMaximumSize(QSize(100, 25))
        self.pushButton.setBaseSize(QSize(89, 25))

        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)

        Laser.setCentralWidget(self.centralwidget)
        self.tableView.raise_()
        self.label_5.raise_()
        self.widget_4.raise_()
        self.widget.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.lineEdit.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.horizontalSlider.raise_()
        self.label_3.raise_()
        self.widget_2.raise_()
        self.widget_3.raise_()
        self.pushButton.raise_()
        self.menubar = QMenuBar(Laser)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1207, 22))
        self.menuMenu = QMenu(self.menubar)
        self.menuMenu.setObjectName(u"menuMenu")
        self.menuVisualizar = QMenu(self.menubar)
        self.menuVisualizar.setObjectName(u"menuVisualizar")
        self.menuInformaci_n = QMenu(self.menubar)
        self.menuInformaci_n.setObjectName(u"menuInformaci_n")
        self.menuOpciones = QMenu(self.menubar)
        self.menuOpciones.setObjectName(u"menuOpciones")
        self.menuApariencia = QMenu(self.menuOpciones)
        self.menuApariencia.setObjectName(u"menuApariencia")
        Laser.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuVisualizar.menuAction())
        self.menubar.addAction(self.menuOpciones.menuAction())
        self.menubar.addAction(self.menuInformaci_n.menuAction())
        self.menuMenu.addAction(self.actionAbrir)
        self.menuMenu.addAction(self.actionGuardar)
        self.menuMenu.addAction(self.actionAbrir_Imagen)
        self.menuMenu.addAction(self.actionSelecionar_camara)
        self.menuMenu.addAction(self.actionExportar_reporte)
        self.menuVisualizar.addAction(self.action3D)
        self.menuVisualizar.addAction(self.action2D)
        self.menuVisualizar.addAction(self.action2D_Menor)
        self.menuVisualizar.addAction(self.action2DGuia)
        self.menuVisualizar.addAction(self.actionTabla_2)
        self.menuInformaci_n.addAction(self.actionAyuda)
        self.menuInformaci_n.addAction(self.actionAbaut)
        self.menuOpciones.addAction(self.menuApariencia.menuAction())
        self.menuApariencia.addAction(self.actionDefault)
        self.menuApariencia.addAction(self.actionDark_Blue)

        self.retranslateUi(Laser)

        QMetaObject.connectSlotsByName(Laser)
    # setupUi

    def retranslateUi(self, Laser):
        Laser.setWindowTitle(QCoreApplication.translate("Laser", u"Perfilador l\u00e1ser", None))
        self.actionGuardar.setText(QCoreApplication.translate("Laser", u"Guardar", None))
        self.actionAbrir_Imagen.setText(QCoreApplication.translate("Laser", u"Seleccionar Imagen", None))
        self.actionSelecionar_camara.setText(QCoreApplication.translate("Laser", u"Selecionar camara", None))
        self.actionTabla.setText(QCoreApplication.translate("Laser", u"Tabla", None))
        self.actionGuardar_tabla.setText(QCoreApplication.translate("Laser", u"Guardar tabla", None))
        self.actionVisualizar_3D.setText(QCoreApplication.translate("Laser", u"Visualizar 3D", None))
        self.action3D.setText(QCoreApplication.translate("Laser", u"3D ", None))
        self.action2D.setText(QCoreApplication.translate("Laser", u"2D Mayor", None))
        self.action2DGuia.setText(QCoreApplication.translate("Laser", u"2D Guia", None))
        self.actionAbaut.setText(QCoreApplication.translate("Laser", u"Abaut", None))
        self.actionDark_Blue.setText(QCoreApplication.translate("Laser", u"Dark-Blue", None))
        self.actionDefault.setText(QCoreApplication.translate("Laser", u"Default", None))
        self.action2D_Menor.setText(QCoreApplication.translate("Laser", u"2D Menor", None))
        self.actionAbrir.setText(QCoreApplication.translate("Laser", u"Abrir", None))
        self.actionAyuda.setText(QCoreApplication.translate("Laser", u"Ayuda", None))
        self.actionExportar_reporte.setText(QCoreApplication.translate("Laser", u"Exportar reporte", None))
        self.actionTabla_2.setText(QCoreApplication.translate("Laser", u"Tabla", None))
        self.actionparametros.setText(QCoreApplication.translate("Laser", u"parametros", None))
        self.label_5.setText(QCoreApplication.translate("Laser", u"Autores: Mario Montero H. & Francisco Racedo N.", None))
        self.label_2.setText(QCoreApplication.translate("Laser", u"Filtro:", None))
        self.label_3.setText(QCoreApplication.translate("Laser", u"0.035", None))
        self.label.setText(QCoreApplication.translate("Laser", u"Pixel size:", None))
        self.label_6.setText("")
        self.label_7.setText("")
        self.pushButton.setText(QCoreApplication.translate("Laser", u"Detener", None))
        self.menuMenu.setTitle(QCoreApplication.translate("Laser", u"Men\u00fa", None))
        self.menuVisualizar.setTitle(QCoreApplication.translate("Laser", u"Visualizar", None))
        self.menuInformaci_n.setTitle(QCoreApplication.translate("Laser", u"Informaci\u00f3n", None))
        self.menuOpciones.setTitle(QCoreApplication.translate("Laser", u"Opciones", None))
        self.menuApariencia.setTitle(QCoreApplication.translate("Laser", u"Apariencia", None))
    # retranslateUi

